export interface Team {
  id: string;
  name: string;
  code: string; // 3-letter code, e.g. ARG, BRA, FRA
  group: string; // A, B, C, D, E, F, G, H
  rating: number; // 1-100 (strength index for realistic simulations)
  flag: string; // emoji flag or CSS styling
}

export interface TeamStats {
  teamId: string;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goalsFor: number;
  goalsAgainst: number;
  goalDifference: number;
  points: number;
  stage: 'groups' | 'r32' | 'r16' | 'qf' | 'sf' | 'final' | 'eliminated' | 'completed';
}

export interface Match {
  id: string;
  stage: 'groups' | 'r32' | 'r16' | 'qf' | 'sf' | 'final';
  group?: string; // for group stage
  homeTeamId: string;
  awayTeamId: string;
  homeScore?: number;
  awayScore?: number;
  isPlayed: boolean;
  commentary?: string; // Simulated drama generated by Gemini
  date: string; // Simulated date/time
  roundIndex: number; // 1, 2, 3 for groups
  penaltyWinnerId?: string; // For knockout stages if there is a draw
}

export interface Participant {
  id: string;
  name: string;
  assignedTeamIds: string[];
  hasPaid: boolean;
  avatarUrl?: string;
}

export interface CollectivConfig {
  entryFee: number;
  potType: 'fixed' | 'dynamic';
  totalPotValue: number; // custom pot size or calculated as participants * entryFee
  currency: string; // USD, GBP, EUR, CAD, AUD
  link: string; // Collectiv link URL
}

export interface LeaderboardRow {
  participantId: string;
  participantName: string;
  hasPaid: boolean;
  teamsCount: number;
  teamStatsList: {
    teamName: string;
    teamCode: string;
    points: number;
    goalDifference: number;
    stage: string;
    isEliminated: boolean;
  }[];
  totalPoints: number;
  totalGoalDifference: number;
  status: 'top' | 'runnerup' | 'worst' | 'normal';
}

export interface SweepstakeState {
  status: 'setup' | 'active' | 'completed';
  participants: Participant[];
  teams: Team[];
  stats: Record<string, TeamStats>; // key: teamId
  matches: Match[];
  collectiv: CollectivConfig;
  currentMatchIndex: number;
  winnerTeamId?: string;
  runnerUpTeamId?: string;
  worstTeamId?: string;
}
